version: '3.8'

services:
  # FastAPI Backend
  api:
    build:
      context: ./multimodal_rag_api
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ADMIN_API_KEY=${ADMIN_API_KEY:-admin123}
    volumes:
      - ./multimodal_rag_api/data:/app/data
      - ./multimodal_rag_api/chroma_db:/app/chroma_db
    restart: unless-stopped

  # Streamlit Frontend  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - API_BASE=http://api:8000
    depends_on:
      - api
    restart: unless-stopped 